/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quieresserminovia;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author Joel
 */
public class Main extends javax.swing.JFrame {

	/**
	 * Creates new form Main
	 */
	public Main() {
            initComponents();
            setLocationRelativeTo(null);
            Image icon3 = Toolkit.getDefaultToolkit().getImage(getClass().getResource("./corazon.jpg"));
            setIconImage(icon3);
            setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
            this.setTitle("Mensaje para ti ♥");
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpMain = new javax.swing.JPanel();
        btnSi = new javax.swing.JButton();
        btnNo = new javax.swing.JButton();
        txtPregunta = new javax.swing.JLabel();
        jlblBack = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(576, 384));
        setResizable(false);

        jpMain.setLayout(null);

        btnSi.setBackground(new java.awt.Color(0, 204, 204));
        btnSi.setForeground(new java.awt.Color(0, 0, 0));
        btnSi.setText("Sí");
        btnSi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiActionPerformed(evt);
            }
        });
        jpMain.add(btnSi);
        btnSi.setBounds(70, 170, 100, 60);

        btnNo.setBackground(new java.awt.Color(0, 204, 204));
        btnNo.setForeground(new java.awt.Color(0, 0, 0));
        btnNo.setText("No");
        btnNo.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                btnNoMouseMoved(evt);
            }
        });
        btnNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoActionPerformed(evt);
            }
        });
        jpMain.add(btnNo);
        btnNo.setBounds(280, 170, 100, 60);

        txtPregunta.setBackground(new java.awt.Color(0, 0, 204));
        txtPregunta.setFont(new java.awt.Font("AntykwaTorunska Medium", 1, 24)); // NOI18N
        txtPregunta.setForeground(new java.awt.Color(51, 51, 255));
        txtPregunta.setText("¿Quieres ser mi novia?");
        jpMain.add(txtPregunta);
        txtPregunta.setBounds(100, 20, 270, 32);

        jlblBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quieresserminovia/cora.jpg"))); // NOI18N
        jpMain.add(jlblBack);
        jlblBack.setBounds(0, 0, 630, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMain, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMain, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoActionPerformed
        btnNo.setText("Sí");
	btnSi.setText("No");
	JOptionPane.showMessageDialog(null, "Sabía que dirías que sí! ❤️\nGracias.","Ah! Te chingé!", JOptionPane.INFORMATION_MESSAGE);
	System.exit(0);
    }//GEN-LAST:event_btnNoActionPerformed

    private void btnSiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiActionPerformed
	JOptionPane.showMessageDialog(null, "Sabía que dirías que si ❤️","Love u Danny ❤️", JOptionPane.INFORMATION_MESSAGE);
	System.exit(0);
    }//GEN-LAST:event_btnSiActionPerformed

    private void btnNoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoMouseMoved
        int w = jpMain.getWidth()-30;
	int h = jpMain.getHeight()-30;
	int y = (int) (Math.random()*(w-1+1)+1);
	int x = (int) (Math.random()*(h-1+1)+1);
	btnNo.setLocation (y, x);
	btnNo.setVisible(true);
    }//GEN-LAST:event_btnNoMouseMoved
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            /*try {
                    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                            if ("Nimbus".equals(info.getName())) {
                                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                                    break;
                            }
                    }
            } catch (ClassNotFoundException ex) {
                    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                    java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }*/
            //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNo;
    private javax.swing.JButton btnSi;
    private javax.swing.JLabel jlblBack;
    private javax.swing.JPanel jpMain;
    private javax.swing.JLabel txtPregunta;
    // End of variables declaration//GEN-END:variables
}
